// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PajoPhone.DataLayer;

#nullable disable

namespace PajoPhone.DataLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PajoPhone.Datalayer.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageProduct")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageProduct = "p1.jpg",
                            ProductColor = "مشکی",
                            ProductName = "محصول 1",
                            ProductPrice = 12000000m
                        },
                        new
                        {
                            Id = 2,
                            ImageProduct = "p1.jpg",
                            ProductColor = "سفید",
                            ProductName = "محصول 2",
                            ProductPrice = 5000000m
                        },
                        new
                        {
                            Id = 3,
                            ImageProduct = "p1.jpg",
                            ProductColor = "مشکی",
                            ProductName = "محصول 3",
                            ProductPrice = 20000000m
                        },
                        new
                        {
                            Id = 4,
                            ImageProduct = "p1.jpg",
                            ProductColor = "مشکی",
                            ProductName = "محصول 4",
                            ProductPrice = 500000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
